cross_links:
  InstallationGuide.adoc: install/
  UserGuide.adoc: user/
  AdministratorGuide.adoc: admin/
  ProgrammersGuide.adoc: dev/
  BestPractices.adoc: dev/kb/
  BeginnersGuide.adoc: beg/
  LinuxInstallationGuide.adoc: linux_inst/
  WebClientLimitations.adoc: web_limits/
  WebProgrammersGuide.adoc: web_dev/
  WorkflowGuide.adoc: workflow/
url_rewrites:
  # these rules are applied first and rewrite complete url with regexp and replace
  - '@html#_Установка_и_конфигурирование_сервера_приложений_и_веб_сервисов_системы': 'html#WebServicesConfig'
  - '@Настройка_клиентского_рабочего_места': 'настройка-клиентского-рабочего-места'
  - '@_настройка-клиентского-рабочего-места': 'настройка-клиентского-рабочего-места'
  - '@_выгрузка_данных_из_представления': 'выгрузка-данных-из-представления'
  - '@_Создание_отчета_с_помощью_связанных_представлений': 'создание-отчета-с-помощью-связанных-представлений'
  - '@^serverSettingCard$': 'AdministratorGuide.adoc#serverSettingCard'
  - '@_routing-examples': 'routing-examples'
  - '@Tessa\. Руководство администратора': 'AdministratorGuide.adoc'
  - '@AdministratorGuide\.html#sample12': 'AdministratorGuide.html#sample2'
  # these rules rewrite only document link, leaving aьфлу ncor part (#...) as is.
  - WorkflowGuide: WorkflowGuide.adoc
  - WebProgrammersGuide: WebProgrammersGuide.adoc
  - WebClientLimitations: WebClientLimitations.adoc
  - AdministratorGuide: AdministratorGuide.adoc
  - ProgrammersGuide: ProgrammersGuide.adoc
  - LinuxInstallationGuide: LinuxInstallationGuide.adoc
  - InstallationGuide: InstallationGuide.adoc
  - UserGuide: UserGuide.adoc
  - Deployment.adoc: AdministratorGuide.adoc
  - Extensions.adoc: ProgrammersGuide.adoc
  - Cards.adoc: ProgrammersGuide.adoc
  - Roles.adoc: ProgrammersGuide.adoc
  - Views.adoc: ProgrammersGuide.adoc
  - Localization.adoc: ProgrammersGuide.adoc
  - Chronos.adoc: ProgrammersGuide.adoc
  - Workflow.adoc: ProgrammersGuide.adoc
  - Routes.adoc: ProgrammersGuide.adoc
  - Tests.adoc: ProgrammersGuide.adoc
  - SmartMergeAPI.adoc: ProgrammersGuide.adoc
  - BestPractices.adoc: ProgrammersGuide.adoc
headers:
  InstallationGuide.adoc:
    Состав поставки: description.md
    Системные требования для серверов Windows и клиентских приложений: requirements.md
    Установка TESSA для серверов Windows: windows.md
    Настройка почтовых уведомлений и мобильного согласования: mail.md
    Публикация приложений: publishing.md
    Инсталлятор Tessa Applications: tessa_apps.md
    Настройки сервера: settings.md
    Проверка установки: validation.md
    Расширенные настройки сервера: adv_settings.md
    Поиск по сообщениям в Обсуждениях: conversations.md
    Дополнительные настройки для web-клиента: web.md
    Установка второго экземпляра Tessa на этом же сервере приложений: second_instance.md
    Локальная установка без настройки IIS: no_iis.md
    Установка платформы TESSA в среде управления контейнерами Docker: docker.md
    Заключение: wrapping_up.md
    Возможные проблемы: troubleshooting.md
  UserGuide.adoc:
  AdministratorGuide.adoc:
  ProgrammersGuide.adoc:
    # do not create a .md file from this chapter
    Методики разработки в Tessa: <skip chapter>
idmap_fallbacks:
  # if id not found in the ProgrammersGuide.adoc idmap, then try to find it in the BestPractices.adoc idmap.
  ProgrammersGuide.adoc: BestPractices.adoc