cross_links:
  InstallationGuide.adoc: install/
  UserGuide.adoc: user/
  AdministratorGuide.adoc: admin/
  ProgrammersGuide.adoc: dev/
  BestPractices.adoc: dev/kb/
  BeginnersGuide.adoc: beg/
  LinuxInstallationGuide.adoc: linux_inst/
  WebClientLimitations.adoc: web_limits/
  WebProgrammersGuide.adoc: web_dev/
  WorkflowGuide.adoc: workflow/
  ReleaseNotes.adoc: rn/
url_rewrites:
  # these rules are applied first and rewrite complete url with regexp and replace
  - '@html#_Установка_и_конфигурирование_сервера_приложений_и_веб_сервисов_системы': 'html#WebServicesConfig'
  - '@Настройка_клиентского_рабочего_места': 'настройка-клиентского-рабочего-места'
  - '@_настройка-клиентского-рабочего-места': 'настройка-клиентского-рабочего-места'
  - '@_выгрузка_данных_из_представления': 'выгрузка-данных-из-представления'
  - '@_Создание_отчета_с_помощью_связанных_представлений': 'создание-отчета-с-помощью-связанных-представлений'
  - '@^serverSettingCard$': 'AdministratorGuide.adoc#serverSettingCard'
  - '@_routing-examples': 'routing-examples'
  - '@Tessa\. Руководство администратора': 'AdministratorGuide.adoc'
  - '@AdministratorGuide\.html#sample12': 'AdministratorGuide.html#sample2'
  # these rules rewrite only document link, leaving aьфлу ncor part (#...) as is.
  - WorkflowGuide: WorkflowGuide.adoc
  - WebProgrammersGuide: WebProgrammersGuide.adoc
  - WebClientLimitations: WebClientLimitations.adoc
  - AdministratorGuide: AdministratorGuide.adoc
  - ProgrammersGuide: ProgrammersGuide.adoc
  - LinuxInstallationGuide: LinuxInstallationGuide.adoc
  - InstallationGuide: InstallationGuide.adoc
  - UserGuide: UserGuide.adoc
  - Deployment.adoc: AdministratorGuide.adoc
  - Extensions.adoc: ProgrammersGuide.adoc
  - Cards.adoc: ProgrammersGuide.adoc
  - Roles.adoc: ProgrammersGuide.adoc
  - Views.adoc: ProgrammersGuide.adoc
  - Localization.adoc: ProgrammersGuide.adoc
  - Chronos.adoc: ProgrammersGuide.adoc
  - Workflow.adoc: ProgrammersGuide.adoc
  - Routes.adoc: ProgrammersGuide.adoc
  - Tests.adoc: ProgrammersGuide.adoc
  - SmartMergeAPI.adoc: ProgrammersGuide.adoc
  - BestPractices.adoc: ProgrammersGuide.adoc
headers:
  InstallationGuide.adoc:
    Состав поставки: description.md
    Системные требования для серверов Windows и клиентских приложений: requirements.md
    Установка TESSA для серверов Windows: windows.md
    Настройка почтовых уведомлений и мобильного согласования: mail.md
    Публикация приложений: publishing.md
    Инсталлятор Tessa Applications: tessa_apps.md
    Настройки сервера: settings.md
    Проверка установки: validation.md
    Расширенные настройки сервера: adv_settings.md
    Поиск по сообщениям в Обсуждениях: conversations.md
    Дополнительные настройки для web-клиента: web.md
    Установка второго экземпляра Tessa на этом же сервере приложений: second_instance.md
    Локальная установка без настройки IIS: no_iis.md
    Установка платформы TESSA в среде управления контейнерами Docker: docker.md
    Заключение: wrapping_up.md
    Возможные проблемы: troubleshooting.md
  LinuxInstallationGuide.adoc:
    Системные требования для серверов Linux: requirements.md
    Установка TESSA: install.md
    Установка на Ubuntu / Debian / Astra Linux: ubuntu.md
    Установка на Linux Mint: mint.md
    Установка на CentOS / Fedora / РЕД ОС: centos.md
    Установка на Calculate Linux: calculate.md
    Установка на SUSE Linux Enterprise / OpenSUSE: suse.md
    Установка на ALT Linux: alt.md
    Обновление на новую сборку платформы: upgrade.md
    Миграция базы данных: migration.md
    Настройка Unix-сокетов и нескольких рабочих процессов: workers.md
    Часто решаемые задачи: more.md
  UserGuide.adoc:
  AdministratorGuide.adoc:
  ProgrammersGuide.adoc:
    Расширения: extensions.md
    Работа с карточками объектов: objects.md
    Ролевая модель: roles.md
    Представления: views.md
    Локализация: localization.md
    Сервис Chronos: chronos.md
    Разработка бизнес-процессов: low_level_workflow.md
    Маршруты: routes.md
    Автоматические тесты NUnit: unit_tests.md
    API Слияния объектов: smart_merge.md
    # do not create a .md file from this chapter
    Методики разработки в Tessa: <skip chapter>
  ReleaseNotes.adoc:
    Версия 3.6: 3.6.md
    Патч 3.5.0.8 (13.04.2021): 3.5.0.8.md
    Патч 3.5.0.7 (13.03.2021): 3.5.0.7.md
    Патч 3.5.0.6 (13.01.2021): 3.5.0.6.md
    Патч 3.5.0.5 (26.12.2020): 3.5.0.5.md
    Патч 3.5.0.4 (29.10.2020): 3.5.0.4.md
    Патч 3.5.0.3 (27.09.2020): 3.5.0.3.md
    Патч 3.5.0.2 (24.08.2020): 3.5.0.2.md
    Патч 3.5.0.1 (08.06.2020): 3.5.0.1.md
    Версия 3.5 (04.06.2020): 3.5.md
    Версия 3.4 (13.11.2019): 3.4.md
    Версия 3.3.1 (16.07.2019): 3.3.1.md
    Версия 3.3 (17.05.2019): 3.3.md
    Версия 3.2 (05.02.2019): 3.2.md
    Версия 3.1.1 (11.12.2018): 3.1.1.md
    Версия 3.1 (01.12.2018): 3.1.md
    Версия 3.0.1 (17.11.2018): 3.0.1.md
    Версия 3.0 (12.11.2018): 3.0.md
idmap_fallbacks:
  # if id not found in the ProgrammersGuide.adoc idmap, then try to find it in the BestPractices.adoc idmap.
  ProgrammersGuide.adoc: BestPractices.adoc