site_name: Simple project for debugging *.md pages
theme:
  name: material
  language: ru
plugins:
  - search
  - macros
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - mdx_truly_sane_lists # https://github.com/mkdocs/mkdocs/issues/545
  - smarty
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
